- project:
    templates:
      - openstack-python-jobs-neutron
      - openstack-python35-jobs-neutron
      - openstack-python36-jobs-neutron
      - openstack-python37-jobs-neutron
      - publish-openstack-docs-pti
      - release-notes-jobs-python3
      - check-requirements
      - periodic-stable-jobs-neutron
    check:
      jobs:
        - openstack-tox-lower-constraints:
            # Currently, we cannot specify that we want neutron
            # checked out from master using tox-siblings for this
            # job, so this always fails.
            voting: false
        - openstack-tox-pep8:
            required-projects:
              - openstack/networking-bgpvpn
              - openstack/networking-sfc
        - openstack-tox-py27:
            required-projects:
              - openstack/networking-bgpvpn
              - openstack/networking-sfc
        - openstack-tox-py35:
            required-projects:
              - openstack/networking-bgpvpn
              - openstack/networking-sfc
        - openstack-tox-py36:
            required-projects:
              - openstack/networking-bgpvpn
              - openstack/networking-sfc
        - openstack-tox-py37:
            required-projects:
              - openstack/networking-bgpvpn
              - openstack/networking-sfc
        - openstack-tox-cover:
            required-projects:
              - openstack/neutron
              - openstack/networking-bgpvpn
              - openstack/networking-sfc
        - legacy-tempest-dsvm-networking-bagpipe:
            irrelevant-files:
              - ^(test-|)requirements.txt$
              - ^setup.cfg$
        - legacy-tempest-dsvm-networking-bgpvpn-bagpipe:
            required-projects:
              - openstack/neutron
              - openstack/networking-bgpvpn
              - openstack/networking-sfc
            irrelevant-files:
              - ^(test-|)requirements.txt$
              - ^setup.cfg$
        - legacy-networking-bagpipe-dsvm-fullstack:
            required-projects:
              - openstack/neutron
              - openstack/networking-bgpvpn
              - openstack/networking-sfc
            voting: false
    gate:
      jobs:
        - openstack-tox-pep8:
            required-projects:
              - openstack/networking-bgpvpn
              - openstack/networking-sfc
        - openstack-tox-py27:
            required-projects:
              - openstack/networking-bgpvpn
              - openstack/networking-sfc
        - openstack-tox-py35:
            required-projects:
              - openstack/networking-bgpvpn
              - openstack/networking-sfc
        - openstack-tox-py36:
            required-projects:
              - openstack/networking-bgpvpn
              - openstack/networking-sfc
        - openstack-tox-py37:
            required-projects:
              - openstack/networking-bgpvpn
              - openstack/networking-sfc
        - legacy-tempest-dsvm-networking-bagpipe:
            required-projects:
              - openstack/neutron
              - openstack/networking-bgpvpn
              - openstack/networking-sfc
            irrelevant-files:
              - ^(test-|)requirements.txt$
              - ^setup.cfg$
        - legacy-tempest-dsvm-networking-bgpvpn-bagpipe:
            required-projects:
              - openstack/neutron
              - openstack/networking-bgpvpn
              - openstack/networking-sfc
            irrelevant-files:
              - ^(test-|)requirements.txt$
              - ^setup.cfg$
